package net.gameoflife.enumeraciones;

public enum TipoEvento {
    REPRODUJO,
    CLONO,
    AGUA_APARECIO,
    COMIDA_APARECIO,
    MONTE_APARECIO,
    TESORO_APARECIO,
    BIBLIOTECA_APARECIO,
    POZO_APARECIO,
    AGUA_ELIMINADO,
    COMIDA_ELIMINADO,
    MONTE_ELIMINADO,
    TESORO_ELIMINADO,
    BIBLIOTECA_ELIMINADO,
    POZO_ELIMINADO,
    AGUA_APLICADO,
    COMIDA_APLICADO,
    MONTE_APLICADO,
    TESORO_APLICADO,
    BIBLIOTECA_APLICADO,
    POZO_APLICADO,
    INDIVIDUO_APARECE,
    INDIVIDUO_REPRODUCE,
    INDIVIDUO_MUEVE,
    INDIVIDUO_MUERE,
    RECURSO_DESAPARECE
}
